### ISSUE TITLE
Inject UIScoped bean in Interceptor doesn't work for Stateless InvocationContext

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#101]
**Originally by _geert3_**

---

Attached is the code for a "simple" test. The concept is as follows:
- We have a service method TestService.doLocked()
- Using a custom annotation @Lock we declare that this method is to be locked.
- Our LockInterceptor intercepts the @Lock annotation and performs the locking around the invoke of the annotated call.
- The LockClient is injected in the Interceptor to do the actual locking (note it doesn't actually do any locking as this is not relevant to reproduce the issue).
- LockClient is @UIScoped as we want each UI (tab) to  have its own locks, i.e. actions in different tabs would lock each other.

Now the issue: if TestService is @Stateless, the LockClient object seen by the LockInterceptor is always the same object, no matter from which UI it is invoked - whereas it should be a different object for every UI.

To reproduce, launch the attached project in Wildfly 8, browse to http://localhost:8080/UIScopedBug/ and click on the button.
The following output will go to stdout:

```
11:23:58,915 INFO  [stdout] (default task-5) bug.LockClient@13759f3a.lock() in UI 0
11:23:58,916 INFO  [stdout] (default task-5) Please lock me
11:23:58,916 INFO  [stdout] (default task-5) bug.LockClient@13759f3a.unlock() in UI 0
```

Now do the same from a different tab:

```
11:24:04,424 INFO  [stdout] (default task-2) bug.LockClient@13759f3a.lock() in UI 1
11:24:04,424 INFO  [stdout] (default task-2) Please lock me
11:24:04,427 INFO  [stdout] (default task-2) bug.LockClient@13759f3a.unlock() in UI 1
```

Notice the same LockClient object, but a different UIId.
You can even press F5, or even remove the JSESSIONID cookie, the object will remain the same. In other words the @UIScope annotation on the LockClient isn't working as expected.

One workaround is to make the TestService @UIScoped too. In that case the LockInterceptor sees a different LockClient object when called from different tabs.
This is not desirable as the TestService doesn't contain state that we want to limit to the UI scope.

Another workaround is to make the LockClient @SessionScoped (while the TestService remains @Stateless), in which case the LockInterceptor correctly sees a different LockClient object in different HTTP Sessions. IMHO this is also proof that the mechanism as such (i.e. injecting an @xxxScoped bean while intercepting a @Stateless service) is supposed to work. In our case however @SessionScoped is undesirable as we want locks to work per UI, not per Session.

Hopefully this explanation is a bit clear.
Tested with both 7.2.1 and 7.4.0 alpha, running inside Wildfly 8.0 (JavaEE7)

---

 Imported from https://dev.vaadin.com/ issue #13959

**Comment by pleku** [comment]
Old v7 issue without any interaction for a long time - closing the issue. In case this is still a problem with v8, please open a new issue.
