### ISSUE TITLE
Vaadin-CDI, UIScope's inheritance from Session/ApplicationScope

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#102]
**Originally by @peterl1084**

---

Would it be feasible or possible to make @UIScoped "dependent" on @SessionScoped through "scope inheritance". There are usecases when for example CDI-events should be sent from @ApplicationScoped bean to multiple @UIScoped beans with IF_EXISTS reception mechanism.

Similar kind of functionality is already available in Vaadin/Spring integrations.

If the above is not wanted, another ticket about being able to send a CDI-event from @Session/@ApplicationScoped to @UIScoped bean with some other mechanism would be necessary. 

---

 Imported from https://dev.vaadin.com/ issue #14071

**Comment by TatuLund** [comment]
As a workaround you can implement mechanism similar to this one https://github.com/TatuLund/cdi-demo/commit/a9b6a5af412fa3794368471e782402f2d7b9863a
