### ISSUE TITLE
CDIViewProvider returns a wrong instance for UIScoped views

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#134]
**Originally by @tomivirkki**

---

CDIViewProvider can return a wrong instance for views that are in the UI scope. This is probably due to using the BeanManager with a newly created CreationalContext for fetching the bean.

A currently failing test case for this can be found [here](https://github.com/tomivirkki/cdi-mvp/blob/master/src/test/java/org/vaadin/addon/cdimvp/test/TestCDIMVP.java#L140-L166).

---

 Imported from https://dev.vaadin.com/ issue #15108

**Comment by amahdy** [comment]
The bug is still alive https://vaadin.com/forum/#!/thread/16871878

Vaadin CDI Add-on 2.0.0

**Comment by tsuoanttila** [comment]
As mentioned in the other ticket on the same topic, fixed in 3.0.0.alpha1

**Comment by pleku** [comment]
Apparently fixed but not closed.
