### ISSUE TITLE
Producer and injection in CDIUI cause NPE

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#146]
**Originally by _Juuso Valli_**

---

Having a producer in the UI works fine, and injecting into the UI works fine, but if you have a producer in the UI and use it to inject something into the UI an NPE is thrown.

Steps to reproduce:
@CDIUI("")
public class TestUI extends UI {

```
@Produces Logger produceLogger() {
    return Logger.getLogger(this.getClass());
}

@Inject
Logger logger;

@Override
protected void init(VaadinRequest request) {
    // TODO Auto-generated method stub

}
```

}

This is most likely caused by UIScopedContext attempting to wrap the contextual during UI creation, even though there is a UIBean in CurrentInstance.

---

 Imported from https://dev.vaadin.com/ issue #15304

**Comment by TatuLund** [comment]
I think this is not a correct way to use producer for Logger. In most cases you won't need more than one instance of logger in your app. Hence the proper way is to create the producer in Singleton class, like here

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/LoggerProducer.java

After which you can then Inject logger in UI 

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/MyVaadinUI.java#L44

or View

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/views/admin/AdminPresenter.java#L23
