### ISSUE TITLE
JaasAccesControl is injected in CdiViewProvider when alternative AccessControl is defined.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#149]
**Originally by _joe32_**

---

When I created my custom AccessControl with @Alternative and definition in beans.xml it works in my project's classes with no problem. But not in CdiViewProvider. I found it when I used RolesAllowed annotation and CdiViewProvider#isUserHavingAccessToView method is invoked. Maybe JaasAccessControl should be Alternative?  

---

 Imported from https://dev.vaadin.com/ issue #15372

**Comment by famod** [comment]
Probably the same problem as in #167 (which contains a workaround using Deltaspike).

**Comment by tsuoanttila** [comment]
Documentation improvement ticket opened. Closing this issue.
