### ISSUE TITLE
Remove Class-Path entry in MANIFEST.MF of vaadin-cdi

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#151]
**Originally by _rmuller@xiam.nl_**

---

The Class-Path does not make sense in the context of Vaadin usage and WildFly complains about it (which is good imho):

Class Path entry vaadin-shared-7.3.1.jar in /content/rangifer.war/WEB-INF/lib/vaadin-cdi-1.0.2.jar  does not point to a valid jar for a Class-Path reference.

---

 Imported from https://dev.vaadin.com/ issue #15466

**Comment by hesara** [comment]
Fix will be at least in 3.0.0.alpha1, but we can also consider back-porting it to earlier branches.
