### ISSUE TITLE
Wrong plug-in configuration in cdi-tutorial POM

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#154]
**Originally by @amahdy**

---

https://github.com/vaadin/cdi-tutorial/blob/master/pom.xml

Missing plug-in version numbers:

For jetty-maven-plugin
For maven-compiler-plugin

In addition, the project should use the Jetty plug-in from org.eclipse.jetty, not org.mortbay.jetty

---

 Imported from https://dev.vaadin.com/ issue #16588

**Comment by pleku** [comment]
I don't think this is anymore valid for the tutorial.
