### ISSUE TITLE
Vaadin 7.4.8 CDI Push protocol websocket fail

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#159]
**Originally by _kolle_86_**

---

Hope this is not a duplicate ticket.

I have problem with CDI add on + Push (Push can not use Websocket protocol with CDI, just long-polling)
When I include CDI add-on, my client debug shows: 

WildFly 8.2.final, (tried 9.0Cr1 also and Tomcat 8.0).
Vaadin 7.4.8 (tried, 7.5.0.beta3 and 7.6.0.alpha1)
CDI (latest.release) 1.0.2

```
207ms Establishing push connection
278ms Push connection closed
281ms Push connection using primary method (websocket) failed. Trying with long-polling
308ms Push connection established using long-polling
```

Its just test CDI app:

```

@Theme("pushtestcdi")
@Push
@CDIUI(value="")
public class PushtestCdiUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

    }

}

```

Without CDI, transport protocol is websocket and everything is alright.
I couldn't find solution on other posts on forum with this subject...

---

 Imported from https://dev.vaadin.com/ issue #18260

**Comment by mshabarov** [comment]
This ticket is upon the same topic https://github.com/vaadin/cdi/issues/143#issue-180043347

**Comment by pleku** [comment]
Old v7 issue which is only valid for extended support customers. Otherwise we'll probably never get to this due to other priorities - closing the issue.
