### ISSUE TITLE
CDIUI injection does not work for sub-urls

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#165]
**Originally by _mvysny2_**

---

I have a UI object annotated with @CDIUI(""). Having    

@WebServlet(urlPatterns # "/*", name"MyUIServlet", asyncSupported = true)
@VaadinServletConfiguration(ui # MyUI.class, productionModefalse)
public static class MyUIServlet extends VaadinCDIServlet {
}

in my UI works correctly if your request is http://localhost:8080/ . However, when you try to fetch, say, http://localhost:8080/bla , the UI instantiates, but no injections are made and the app will eventually crash with NPE. I believe that the CDI plugin should trigger injection even when the UI URL is weird; after all, user can browse invalid URL and then wonder why the server crashes.

---

 Imported from https://dev.vaadin.com/ issue #18993

**Comment by pleku** [comment]
Old issue which we'll probably never get to it due to other priorities - closing the issue.
