### ISSUE TITLE
UIScopedContext leaks closed UIs

### ISSUE THREAD

**Issue by kumm** [vaadin/cdi#176]
All closed UI is referenced from UIScopedContext storageMap until http session invalidation.

Simple to reproduce, just build a helllo-world vaadin app with one CDIUI.
Run it, and refresh the page in the browser. Every time you refresh, an UI with closing=true leaked from UIScopedContext. - I know i can use PreserveOnRefresh.
But same result when opening the UI in a new tab, closing it, and waiting 3 heartbeatInterval.

I think UIScopedContext should free the UI after it's closed.

Here is a screenshot from jvisualvm. [![vaadincdijvm1.png](https://s11.postimg.org/luw1u4yfn/vaadincdijvm1.png)](https://postimg.org/image/gw8jflumn/)

Tested with CDi addon 1.0.3, and vaadin 7.7.2.

**Comment by kumm** [comment]
After some investigation in the source code i can explain the intended behavior.
Closed UIs of a vaadinsession should destroy, and free form UIContext.storageMap on the first viewChange event after a five second timeout.
But actually it does not work.

**Comment by m--stein** [comment]
Same problem here.
Any chance that the fix from kumm will be integrated soon?

**Comment by doggy-dev** [comment]
This seems related to #169

**Comment by kumm** [comment]
@doggy-dev : There are multiple problems in this add-on with destroying contextual instances. #169 is about viewcontext, so not related. This issue is about leaking UIs. 
The pull request #178 for this issue fixes destroying of UIs, not Views ( not even UIScoped beans ).
But we can say issue #155 is closely related, and fixed by the pull request.

**Comment by zeitiger** [comment]
I have a similar problem with `com.vaadin.cdi.internal.AbstractVaadinContext#storageMap` because in application `storageMap.remove(...)` is not called. 
The pull request #184 doesn't work for me :-(

**Comment by kumm** [comment]
@zeitiger can you share the details?
How do you test it exactly? (cleanup after 5 seconds on the next view navigation should work.)
Can you share a simple project (or integration test) to reproduce the issue?

**Comment by zeitiger** [comment]
Currently I still make my research and try to understand what exactly happing. The 5 seconds clean up doesn't work for me. New session could be created within my application (incognito browser or logout), but the session will never clean up. It is quite hard to track down why something doesn't happen.

**Comment by zeitiger** [comment]
My problem was more combination of 3rd party libs. We used Shiro in a Servlet independent mode, that replace HttpSession, but not notify over HttpSessionListener were Vaadin count on and so Vaadin CDI fail to clean up because VaadinSession never get closed.

**Comment by hesara** [comment]
Fix included in 2.0.0.rc1, can consider later picking this to 1.x.

**Comment by famod** [comment]
> can consider later picking this to 1.x.
+1 from me. Vaadin 8 is not even final so basically all productive Vaadin installations will be running 7.x or below and probably cannot be updated right away.

**Comment by hesara** [comment]
Picked to 1.0 branch to be released with the next Vaadin CDI 1.x version.

**Comment by hesara** [comment]
This will also be included in 1.0.4.
