### ISSUE TITLE
CDI in Vaadin 8

### ISSUE THREAD

**Issue by heruan** [vaadin/cdi#181]
I'm testing Vaadin 8.0.0.alpha6 and it's great! The only feature I can't migrate from 7 seems to be CDI in JavaEE. Am I missing something? Maybe a hidden repo for a vaadin-cdi snapshot? Any other chance to get CDI work on Vaadin 8?

**Comment by hesara** [comment]
We are planning to release a Vaadin 8 compatible version of the CDI and Spring add-ons around the time we release 8.0.0.beta1.

I quickly tested the CDI add-on with the latest 8.0-SNAPSHOT, and the add-on itself didn't require any other changes than change of dependency and recompilation (not even sure if that was necessary), whereas in my test application I had to do a bit more Vaadin 8 migration.

Is there something specific that is not working for you?

**Comment by hesara** [comment]
(Note, though, that the automated tests in the add-on depend on old versions of Arquillian etc. and will need to be updated for them to work, so I used -DskipTests in my quick testing. Thus, no full unit and integration tests have been run yet.)

**Comment by hesara** [comment]
Fixed tests in the add-on (in master) and added a vaadin-8 branch, which only has some minor POM changes.

**Comment by heruan** [comment]
I may be doing something wrong, but I'm getting this Exception with the latest snapshot:
```
java.lang.NoSuchMethodError: com.vaadin.cdi.server.VaadinCDIServletService.addSessionInitListener(Lcom/vaadin/server/SessionInitListener;)V
	at com.vaadin.cdi.server.VaadinCDIServletService.<init>(VaadinCDIServletService.java:73)
	at com.vaadin.cdi.server.VaadinCDIServlet.createServletService(VaadinCDIServlet.java:44)
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:227)
```

**Comment by heruan** [comment]
Dependency cache problem, forcing an update fixed this. Leave open for further updates during 8.0 development!

**Comment by myungsunscott** [comment]
@heruan I'm suddenly experiencing the same Exception using CDI on a tomee plugin:

Everything builds successfully with `mvn clean install` and deploys to the Tomee server fine. Then when I try loading the application, I see your exception.

Also tried clearing the maven cache, but still no success.

May I ask what steps did you took to resolve this issue?

```
java.lang.NoSuchMethodError: com.vaadin.cdi.server.VaadinCDIServletService.addSessionInitListener(Lcom/vaadin/server/SessionInitListener;)Lcom/vaadin/shared/Registration;
	com.vaadin.cdi.server.VaadinCDIServletService.<init>(VaadinCDIServletService.java:73)
	com.vaadin.cdi.server.VaadinCDIServlet.createServletService(VaadinCDIServlet.java:44)
	com.vaadin.server.VaadinServlet.init(VaadinServlet.java:227)
	org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
```

**Comment by Legioth** [comment]
@myungsunscott That exception means that the `VaadinCDIServletService` class that is being used is compiled against Vaadin Framework 7 instead of version 8. This means that your classpath contains version 1.x of the CDI plugin instead of version 2.0.0.beta1. You should make sure you have updated the version number in any relevant `pom.xml` and maybe also check that there aren't any plugin jars cached in any other location that might be picked up by the server.

**Comment by myungsunscott** [comment]
@Legioth Thanks! There were indeed hidden dependency issues in a couple `pom.xml` that are in use.

Working now though.
