### ISSUE TITLE
revise UIScoped bean destroy behavior

### ISSUE THREAD

**Issue by kumm** [vaadin/cdi#191]
On destroy i mean cleanup of the context and triggering @preDestroy method on contextual instances.
According to the source code, the current intended behaviour is:
- cleanup 5 second (or more) later than ui detach, during an other vaadin request.
- such a cleanup should trigger by a viewchange event
- on session destroy don't wait, cleanup immediately.

There are some problems with it. First, it is not working, as reported in issues #176, #158 #155 . 
It can be fixed. All right, at least i have fixes ( #184 ). 

But i don't believe it should work this way. 
- it's weird. Why 5 seconds, why on an other request, why after view navigation?
- it's inconsistent. Behaves differently on ui close, and session close.
- it makes view navigation mandatory. Without view navigation uis won't destroy until session destroy.

I've found one reason commented in AbstractVaadinContext.
> We introduce a cleanup delay because the UI gets referred to
> later in the core cleanup process. If the UI is proxied this will
> cause a new UI to be initialized in some CDI implementations (for
> example Apache OpenWebBeans 1.2.1)

I would say all proper CDI implemetations work this way.

But are there other reasons?
Is anybody out there using normal scoped UIs?
Currently i'm experimenting with immediate ui destroy on detach with non-normal scoped uis. So far so good.

**Comment by famod** [comment]
This all makes a lot of sense, but:
> Is anybody out there using normal scoped UIs?

It seems I have to do so when I want to use Deltaspike's ``BeanProvider.injectFields(...)`` to perform Injection into a non-managed bean (into a ``Window``/``MWindow`` for instance).
``@UIScoped`` does not work (no bean can be found), but ``@NormalUIScoped`` _does_ work.

**Comment by kumm** [comment]
@famod I think it should work with BeanProvider.getContextualReference at the place where you really need to use the UI instance. - so do not cache as a property

**Comment by kumm** [comment]
I've reimplemented the contexts in a [fork](https://github.com/wbstr/vaadin-alt-cdi). Immediate UI destroy on detach, and many other changes. See readme, any feedback are welcome. 
To be released soon at vaadin directory.

**Comment by famod** [comment]
Does your fork support Vaadin 7 or just 8?

**Comment by kumm** [comment]
@famod in fact i still use it mostly with vaadin 7. Pushed to vaadin7 branch.

**Comment by tsuoanttila** [comment]
Is this issue still relevant with the master branch and the 3.0 ?

**Comment by kumm** [comment]
No, it is not relevant with 3.0.
NormalUIScoped UIs not supported, just UIScoped UIs. 
Now UIScoped UIs are destroyed immediately on close.

**Comment by tsuoanttila** [comment]
Closing the ticket, marking to 3.0.0.alpha1
