### ISSUE TITLE
Version 2.0.0 in pom.xml

### ISSUE THREAD

**Issue by heruan** [vaadin/cdi#201]
The `pom.xml` in tag `2.0.0` still has version 2.0-SNAPSHOT and required Vaadin 8.0-SNAPSHOT. I suppose it should have version 2.0.0 and require Vaadin 8.0.0.

**Comment by hesara** [comment]
Our CI server performs versions:set and updates the property vaadin.version as a part of a release build. This was done for the tagged revision, but those changes are not committed from CI to GitHub.
You can see the released POM at http://repo1.maven.org/maven2/com/vaadin/vaadin-cdi/2.0.0/vaadin-cdi-2.0.0.pom .

We should look into using the release plug-in for simple projects such as add-ons, but that is a separate topic.
