### ISSUE TITLE
Inject external classes without cdi annotation

### ISSUE THREAD

**Issue by Romain-P** [vaadin/cdi#208]
I would like to have a singleton (session scoped) of EventBus from google.common but I didn't find the way. Maybe isn't this implemented ?

like
```
@SessionScoped
Eventbus bus;
```

I thought 

> @SessionScoped

 worked on fields.

**Comment by Romain-P** [comment]
@Artur- ?

**Comment by Artur-** [comment]
Hi,

This looks like a generic CDI question which would be better asked on https://vaadin.com/forum or https://stackoverflow.com/
