### ISSUE TITLE
CDI fails to deploy with JAX-WS, JAX-RS Liberty  (CDI 1.0.4) 

### ISSUE THREAD

**Issue by sknitelius** [vaadin/cdi#236]
Just as is the case in #163, there are a couple more classes which are isolated from the Application via OSGI in Liberty:
* com.ibm.ws.jaxws.webcontainer.LibertyJaxWsServlet
* com.ibm.websphere.jaxrs.server.IBMRestServlet

There might be a couple more, it might be safest to ignore com.ibm.* completely. 

Alternativly this problem could be avoided completely by changing the logic to completly ignore ClassNotFoundExceptions and only excplicitly throwing an exception if no VaadinServlet ist found.

I will also raise an issue with Liberty, seems to me that those servlets shouldn't be leaked to the application.

**Comment by sknitelius** [comment]
BTW - I didn't create a pull request for 2.0 - might also want to fix it there.

**Comment by tsuoanttila** [comment]
The currently developed versions of CDI are 3.0 for 8.3+ and 1.0 for 7.7. The 2.0 branch is not recommended to be used anymore as many of known issues with that version have been actually fixed in the 3.0.
