### ISSUE TITLE
How can I get a spring controller working with the same session that the CDI is using?

### ISSUE THREAD

**Issue by brandonseydel** [vaadin/cdi#263]
All - I want to create SPRING Rest controllers utilizing the same session that the vaadin servlet has authenticated already?  How can I go about doing this?

**Comment by kumm** [comment]
Are you sure you want to use both SPRING and CDI addon in the same web application?
Sharing managed beans between the two DI framework does not seem to be a good idea.
But you see the same http session, so directly using it should work. 

To free a root path for spring rest you may need to map `VaadinCdiServlet` to another path instead of root. It is still in WIP according to https://github.com/vaadin/flow/issues/4619.

**Comment by brandonseydel** [comment]
The problem is that I need to share a bean that is used for security between cdi and a spring servlet on Jboss.  Is there any way to achieve this?

**Comment by kumm** [comment]
In a JEE container you can get a contextual Reference for a CDI bean inside any servlet - regardless of this addon -.
For example with deltaspike `BeanProvider.getContextualReference`.
The scope of the bean should not be a Vaadin scope. In this case it should be `@SessionScoped`.

**Comment by brandonseydel** [comment]
It fits those requirements, but when accessing the reference it does not maintain the same information.  I will do more investigation.

**Comment by brandonseydel** [comment]
Here is the method that gets called....  I believe it cannot access VaadinService
public int logon(String var1, String var2) throws ApplicationException, FTPCException {
        byte var3 = 1;

        try {
            HttpServletRequest var4 = (HttpServletRequest)VaadinService.getCurrentRequest();
            var4.login(var1, var2);
            this.securityProxy.login();
            this.setCurrentUserName(var1);
            this.loginFailureCount = 0;
            if (this.getLoggedOnUser().isPasswordExpired()) {
                var3 = 2;
            }

            if (VaadinSession.getCurrent().getSession() != null) {
                this.sessionId = VaadinSession.getCurrent().getSession().getId();
            }

            return var3;
        } catch (Exception var9) {
            RALogger.logException(var9, this, "logon");
            ++this.loginFailureCount;
            if (ExceptionHandler.isFTPCException(var9)) {
                throw (FTPCException)ExceptionHandler.convertException(var9);
            } else {
                ApplicationException var5 = (ApplicationException)ExceptionHandler.convertException(var9);
                if (this.loginFailureCount > 3 && Utility.equals(var5.getMessageID(), "Presenter.Error.LoginFailed")) {
                    var5 = new ApplicationException("It's possible that your account has been disabled or expired.  Please contact your system administrator for assistance.", "Security.Error.LoginFailed.DisableOrExpired", new Object[0]);
                    throw var5;
                } else {
                    try {
                        int var6 = this.securityHandlingProxy.diagnoseLoginFailure(var1, EncryptionUtils.getEncryptedPassword(var2, true));
                        ApplicationException var7;
                        if (var6 == 3) {
                            var7 = new ApplicationException("It's possible that your account has been disabled or expired.  Please contact your system administrator for assistance.", "Security.Error.LoginFailed.DisableOrExpired", new Object[0]);
                            throw var7;
                        }

                        if (var6 == 2) {
                            var7 = new ApplicationException("The user name or password you entered is incorrect.  Please try again.", "Presenter.Error.LoginFailed", new Object[0]);
                            throw var7;
                        }
                    } catch (DatasweepServerException var8) {
                        throw (FTPCException)ExceptionHandler.convertException(var8);
                    }

                    throw var5;
                }
            }
        }
    }

**Comment by kumm** [comment]
There is no current VaadinService, VaadinSession,  VaadinRequest, UI  outside of vaadin request processing.
