### ISSUE TITLE
CDI IT tests fail for latest Flow

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/cdi#272]
Take the project's master branch, use different versions for `vaadin.flow.version` property in the parent poms and run IT tests with `mvn verify -Ptomee`

Expected: tests pass for Flow 1.0-SNAPSHOT, Flow 1.1-SNAPSHOT and Flow 1.2-SNAPSHOT
Actual: 
• tests passe for 1.0-SNAPSHOT
• 1 IT test fails for 1.1-SNAPSHOT
• regular tests fail for 1.2-SNAPSHOT

Tests need to be fixed so that every Flow version is supported.

**Comment by elmot** [comment]
Fixed with #273, #274
