### ISSUE TITLE
@Observes declared in a @CDIView are not invoked with Vaadin 8.9.3

### ISSUE THREAD

**Issue by gofiocode** [vaadin/cdi#306]
I had a Vaadin 8.1.3 working percfectly with your CDI addon, but when I upgraded to Vaadin 8.9.3, I realizaed of this issue: The @Observes declared in a @CDIView are not invoked.
```
I fire an event:
  @Inject private javax.enterprise.event.Event<MyEvent> myEvent;
  ....
  myEvent.fire(new MyEvent(true));

And I observe ot in a @CDIView class:
  void onMyEventObserver(@Observes MyEvent event) {
```

This works ok with Vaadin 8.1.3, but fails if I upgrade to Vaadin 8.9.3 (If the observer is declared in a @UIScoped class, then it also works with Vaadin 8.9.3).

Vaadin 8.1.3 and 8.2.1 >> works OK
Vaadin 8.3.3 and 8.9.3 >> FAILS!

Thnks in advance!

**Comment by TatuLund** [comment]
Is this the same as this one https://github.com/vaadin/cdi/issues/235 ?

**Comment by gofiocode** [comment]
> 
> 
> Is this the same as this one #235 ?

I am glad to confirm that the solution proposed in #235 fixed my issue. We are now using Vaadin 8.11.0 successfully.

Thanks TatuLund!
