### ISSUE TITLE
CDI 12.x SNAPSHOT builds fail

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/cdi#327]
CDI 12.x SNAPSHOT builds for Flow 3.x fail. Here are the links to the builds in TeamCity:
- [Flow CDI 12.0 (Flow 3.0-SNAPSHOT)](https://bender.vaadin.com/viewLog.html?buildId=141147&tab=buildResultsDiv&buildTypeId=Flow_AddOns_FlowCdi120Flow30snapshot) 
- [Flow CDI 12.1 (Flow 3.1-SNAPSHOT)](https://bender.vaadin.com/viewLog.html?buildId=141144&tab=buildResultsDiv&buildTypeId=Flow_AddOns_FlowCdi121Flow31snapshot)
- [Flow CDI 12.1 (Flow 3.2-SNAPSHOT)](https://bender.vaadin.com/viewLog.html?buildId=141149&tab=buildResultsDiv&buildTypeId=Flow_AddOns_FlowCdi121Flow32snapshot)

**Comment by caalador** [comment]
Seems like 12.1 for 3.1 and 3.2 were failing due to the mixed snapshots, but 12.0 for 3.0 is failing with a deployment problem still.

**Comment by joheriks** [comment]
The remaining failure was due to older version of Tomee not liking the new dependency `jackson-datatype-jsr310` introduced in flow 3.2 and 3.0 (but not 3.1!). So it also occurred in 12.1 for 3.2, but the bender job was misconfigured (erroneously used Flow 3.1).
