### ISSUE TITLE
RouteScoped parent layouts shared between RouteScoped Routes are not preserved

### ISSUE THREAD

**Issue by roeltje25** [vaadin/cdi#388]
Recently, the working of RouteScoped has been changed. If a bean has no RouteScopeOwner attached, the lifecycle is bound to the lower most RouteComponent in the navigation chain. Seems sensible.

However. Imagine that a parent RouterLayout with RoutePRefix "parent" has two child route components. "one" and "two". All are RouteScoped. When navigating from one to two using the above "new" logic would and indeed does move the parentlayout out of scope. But should not the ParentLayout in this case be retained within scope?

Indeed when I upgrade Vaadin CDI from 12.0.0 to 13.0.0 some of my code breaks because of exactly this change.

My suggestion / expectation would be that @RouteScoped router layouts would  have a RouteScopeOwner being itself, not the bottom-most target in the navigation chain. This way the RouterLAyouts are preserved when they are shared between subsequent navigation targets.

**Comment by roeltje25** [comment]
I have implemented my way of thinking about keeping the routerlayout in scope during route changes with the same parent layout by adjusting RouteScopedContext. Method getCurrentNavigationTarget on line 292:
```java
        public static Class getCurrentNavigationTarget(UI ui, Bean<?> bean)
        {
            NavigationData data = ComponentUtil.getData( ui, NavigationData.class );
            if( data == null )
            {
                throw new IllegalStateException( String.format(
                        "There is no yet any navigation chain available, " + "so bean '%s' has no scope and may not be injected",
                        bean.getBeanClass( ).getName( ) ) );
            }
            // added following 2 lines
            if( data.getLayouts( ).contains( bean.getBeanClass( ) ) )
                return bean.getBeanClass( );
            return data.getNavigationTarget( );
        }
```

**Comment by mcollovati** [comment]
@roeltje25 may I ask you to provide a minimal code example to reproduce the situation you described?

**Comment by roeltje25** [comment]
Ok. It took me a while. Please review the demonstration of the example below. It seems that the issue is not with injected instances of RouteScoped instances with RouterLayouts (parents) With @RouteScopeOwner. It is actually related to issue #390 . That issue got solved, but there is still an issue as demonstrated in example.

What is happening? I send a Bleep event when in OtherView a button is clicked. This Bleep is observed in ParentLayout. However, the event is not observed. After investigating the firing of the event what happens is that the resolved owner called by getOwner in RouteScopedContext defaults to the method getCurrentNavigationTarget which will return the deepest child. and as such will not find the ParentLayout as a target to call the observes method.

What it should do is also try to find the Bean<?> in getOwner (or getCurrentNavigationTarget) in the whole navigation chain. Where it should find the ParentLayout and correctly deliver the event.

Example (branch)
https://github.com/roeltje25/vaadin-cdi-skeleton-starter-demo/tree/issue-388
