### ISSUE TITLE
Conditional observers in @RouteScoped components not working with Weld?

### ISSUE THREAD

**Issue by nluckas** [vaadin/cdi#390]
We are using Vaadin 23 (23.0.9) with vaadin-cdi (14.0.0) and are having problems with conditional observers in @RouteScoped components.
We are running on Tomcat 9 and use Weld (3.1.9.Final) as our CDI implementation. Our current problem is that we get the following exception when firing an event that is observed in a @RouteScoped component:

> java.lang.IllegalStateException: Route owner 'class XXX' instance is not available in the active navigation components chain: the scope defined by the bean 'YYY' doesn't exist.

We believe that the problem are the changes implemented in Vaadin CDI 13.0.0 (https://github.com/vaadin/cdi/releases/tag/13.0.0):

> Trying to use @RouteScope when there is no active route component present is not allowed.

In the Weld implementation we are using, the method getReceiverIfExists (in class ObserverMethodImpl) calls the method getContextualStorage() in class RouteScopedContext. And getReceiverIfExists is called before the reception of the observer is considered. Therefore all classes that have an observer on the event are trying to be received and since not all @RouteScoped classes are in the current navigation chain, the above mentioned error is thrown.

```
Object receiver = getReceiverIfExists(null); //this is where the exception is thrown
if (receiver == null && reception != Reception.IF_EXISTS) {
   // creational context is created only if we need it for obtaining receiver
   // ObserverInvocationStrategy takes care of creating CC for parameters, if needed
   creationalContext = beanManager.createCreationalContext(declaringBean);
   receiver = getReceiverIfExists(creationalContext);
}
if (receiver != null) {
   sendEvent(event, receiver, creationalContext);
}
```
Right now, we are not able to use conditional observers in @RouteScoped classes. Is there a way to fix this?
Link to example project: https://github.com/nluckas/vaadincdiwithweldexample

**Comment by mshabarov** [comment]
Thank you for reporting this issue. Could you please provide an example project reproducing this error?

**Comment by nluckas** [comment]
You can find an example project here: https://github.com/nluckas/vaadincdiwithweldexample. Should be running on Tomcat 9.

**Comment by mcollovati** [comment]
Can replicate the issue with the example project.
Perhaps `RouteScopedContext.convertToKey()` should throw `IllegalStateException` only if `getContextualStorage(Contextual<?> contextual,boolean createIfNotExist)` is invoked with `createIfNotExist = true`

**Comment by roeltje25** [comment]
I also have this issue. I worked around it using a bytebuddy hack that handles createIfNotExist better.  I think the illegalstateexception is indeed misplaced in case createIfNotExist is false.

so +1 for me!
