### ISSUE TITLE
Vaadin 23 CDI application can't see @Routes within Maven sub-modules

### ISSUE THREAD

**Issue by aceraces** [vaadin/cdi#423]
I have a Vaadin(23) CDI project. It's supposed to be a multi-module Maven project with a parent WAR that contains JARs with components that have Flow `@Route` that should be available in parent application, but whenever I run Wildfly(26) on the parent's war, it can't see any routes within Maven sub-modules. 

It also seems that `@EnableVaadin` annotation would be the answer in a Spring Boot application, which sadly isn't the case here. I haven't found anything equivalent sadly.

**Comment by mcollovati** [comment]
I have created a project based on the https://github.com/vaadin/skeleton-starter-flow-cdi and added a dependency to another artifact that contains only a view with `@Route` annotation.
When I started WildFly (26.1.2.Final) I was able to navigate to the route defined in the external artifact without any issue.

To be noted that `@Route` is not a bean defining annotation, so if the war/jar have a beans.xml set with `bean-discovery-mode="annotated"` the views should be annotated with `@CdiComponent`.

This should however only affect injection and lifecycle annotations (e.g `PostConstruct`) not being invoked, but if the view has a default constructor it should be accessible.

Are there any errors on server logs?
Could you provide a sample project that reproduces the problem?

**Comment by mcollovati** [comment]
Sorry, but until you can provide the code that reproduces the issue, there is nothing that we can do. Until that, we consider this an issue specific to your application. Please add comments on the issue if you discover a root cause not dependent on your application and can provide the code to reproduce the issue
