### ISSUE TITLE
@Postconstruct  not called

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#56]
**Originally by _ronald.vermeire_**

---

In vaadin-cdi-example InjectableLayout initLayout() is not called when run with mvn tomee:run

When run with mvn jboss-as:run it gives a NullPointerException in InjectableLayout constructor. I could workaround this by adding @CDIUI to InjectableLayout.

---

 Imported from https://dev.vaadin.com/ issue #11594

**Comment by madduci** [comment]
This applies also to Vaadin 12 and latest plugin version 10.1.0
