### ISSUE TITLE
CDIUIProvider has a broken mapping function

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#93]
**Originally by @tmattsso**

---

When using JAAS, sometimes the URL after login is something like 

```
.../login.jsp
```

If you have an UI mapped to /, this should obviously match; but the mapper in CDIUIProvider#getUIBeanWithMapping only checks for exact match, which will fail because empty string != "login.jsp".

The matcher should be implemented so that it checks all UIs found and orders them according if they match at all or very well. If no exact match is found, root would still be selected since it does match, only poorly.

---

 Imported from https://dev.vaadin.com/ issue #13246

**Comment by TatuLund** [comment]
CDIUIProvider#getUIBeanWithMapping has been rewritten in v3.0.0 for Vaadin 8, so probably fixed now.

**Comment by pleku** [comment]
Closing as this has apparently been fixed.
