### ISSUE TITLE
Ensure Vaadin CDI works without beans.xml in Java EE 7 containers

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#96]
**Originally by @mstahv**

---

I faced some bizarre issues with Java8-Glassfish 4-cdi alpha1. In case @PostConstruct annotated method had a simple lambda expression, the view didn't get injected. Once I tried with beans.xml file, it suddenly worked. Java EE7 shouldn't need beans.xml file.

Don't know really if this is a Vaadin CDI or Glassfish issue.

Test case (paren commit for this fix):
https://github.com/mstahv/java-ee7-jsfapp-with-vaadinized/commit/e6a1ef2cdbbbaf13a31f76ee67d3e8f945cf0bb4

---

 Imported from https://dev.vaadin.com/ issue #13478

**Comment by pleku** [comment]
Old issue without any feedback for a long time - closing this as it is not a priority. In case this is an issue for someone in v8 or v14, please open a new issue, thanks.
