### ISSUE TITLE
Exception when two CDI UIs are deployed in separate WARs inside of an EAR

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/cdi#97]
**Originally by @vaadin-kim**

---

Bundling two WAR's both containing a @CDIUI into an EAR and deploying it on Glassfish/JBoss will result in an exception:

2014-04-02T14:29:55.600+0300|SEVERE: org.jboss.weld.context.ContextNotActiveException: WELD-001303 No active contexts for scope type com.vaadin.cdi.UIScoped

Test case attached.

---

 Imported from https://dev.vaadin.com/ issue #13526

**Comment by mrts** [comment]
This may be fixed in latest WildFly 12, see https://issues.jboss.org/browse/WELD-2143. Can someone try it out?

**Comment by mrts** [comment]
Great news - multiple WARs now work in a single EAR with Vaadin 10 CDI, at least in WildFly 14.

Here's a sample project to try this out:

https://gitlab.com/mrts/vaadin10-javaee-multiple-wars-in-one-ear

**Comment by peholmst** [comment]
@mrts Please check #282

**Comment by mrts** [comment]
@peholmst Thank you, I will when time allows!

**Comment by mrts** [comment]
@peholmst Thank you, I confirm that it fixes the problem in the test application that I created. Let's see if we run into problems in a larger real life application.
